from django.urls import path,include
from . import views

urlpatterns = [


    path("index/",views.IndexPage,name="index"),
    path("",views.Register,name="register"),
    path("register/",views.Register,name="Register"),
    path("loginuser/",views.LoginUser,name="loginuser"),
    path("homepage/",views.homepage,name="homepage"),
    path("services/",views.services,name="services"),
    path("appointment/",views.Appointment,name="appointment"),
    
    path("blog/",views.Blog,name="blog"),
    path("blogdetail/",views.Blogdetail,name="blogdetail"),
    path("about/",views.About,name="about"),
    path("team/",views.Team,name="team"),
    path("price/",views.Prize,name="price"),
    path("coming-soon/",views.Comingsoon,name="comingsoon"),
    path("project/",views.Project,name="project"),
    path("projectdetail/",views.Projectdetail,name="projectdetail"),
    path("servicedetail/",views.Servicedetail,name="servicedetail"),
    path("teamdetail/",views.Teamdetail,name="teamdetail"),
    path("testimonials/",views.Testimonial,name="testimonials"),
    path("faq/",views.Faq,name="faq"),
    path("comingsoon/",views.Comingsoon,name="comingsoon"),
    path("errorpage/",views.Errorpage,name="errorpage"),
    path("shop/",views.Shop,name="shop"),
    path("shop1/",views.Shop1,name="shop1"),
    path("shop2/",views.Shop2,name="shop2"),
    path("checkout/",views.Checkout,name="checkout"),
    path("cart",views.Cart,name="cart"),
    path("contact/",views.Contact,name="contact"),
    # path("acceptstatus/<int:pk>",views.Acceptstatus,name="acceptstatus"),
    path("acceptance/<int:pk>",views.Acceptance,name="acceptance"),
    path("reject/<int:pk>",views.Reject,name="reject"),
    path("logout/",views.Logout,name="logout"),
    path("statuspage/",views.statuspage,name="statuspage"),
    path("forgotpassword/",views.Forgotpassword,name="forgotpassword"),
    path("rejectpage/",views.Rejectpage,name="rejectpage"),
    path("gold/",views.Goldpage,name="gold"),
    path("silver/",views.Silverpage,name="silver"),
    path("platinum/",views.Platinumpage,name="platinum"),
    path("email/",views.Email,name="email"),
    # path("sellerform/",views.Sellerform,name="sellerform"),
    path("vehiclesell/",views.Vehiclesell,name="vehiclesell"),
    path("sellpage/",views.Sellpage,name="sellpage"),
    path("vehicleinfo/<int:pk>",views.Vehicleinfo,name="vehicleinfo"),
    # path("statustable/",views.Statustable,name="statustable")
    path("membershipform/",views.Membershipform,name="membershipform"),
    path("vehemail/<int:pk>",views.vehEmail,name="vehemail"),
    # path("vehdetails/",views.Vehdetails,name="vehdetails"),
    path("addToCart",views.AddToCart,name="addtocart"),
    path("addcart/<int:pk>",views.AddCart,name="addcart"),
    path("deleteproduct/<int:pk>",views.DeleteProduct,name="deleteproduct"),
    path("verifyotp",views.Verifyotp,name="verifyotp"),
    path("changepass",views.Changepass,name="changepass"),
    path("xx/",views.xx,name="xx"),
    path("Updatecart/<int:pk>",views.Updatecart,name="updatecart"),
    path("thanks/",views.Thanks,name="thanks"),
    path("userprofile",views.Userprofile,name="userprofile"),
    path("passchange",views.Passchange,name="passchange"),
    path("profilepic",views.Profilepic,name="profilepic"),
    path("track",views.Track,name="track"),
    path("trackacc",views.Trackacc,name="trackacc"),
    path("trackveh",views.Trackveh,name="trackveh"),
    path("emergency",views.Emergency,name="emergency"),
    path("editprofile",views.Editprofile,name="editprofile"),
    path("product_details/<int:pk>",views.Productdetails,name="product_details"),
    path("like/<int:pk>",views.Like,name="like"),
    path("cancelorder/<int:pk>",views.Cancelorder,name="cancelorder"),
    path("cancelveh/<int:pk>",views.Cancelveh,name="cancelveh"),   
    #payemnt
    path("payment", views.Payment,name="payment"),
    path('pay/', views.initiate_payment, name='pay'),
    path('callback/', views.callback, name='callback'),
    path('paymentcart',views.Cartpayment,name="paymentcart"),
    path('paybill/<int:pk>',views.Paybill,name='paybill'),
    

    #foreman
    path("editfor",views.Editfor,name="editfor"),
    path("forapproval",views.Forapproval,name="forapproval"),
    path("forapprove/<int:pk>",views.Forapprove,name="forapprove"),
    path("foremanvehicle/",views.foremanvehicle,name="foremanvehicle"),
    path("findex/",views.Foremanindex,name="findex"),   
    path("forcard",views.Forcard,name="forcard"),
    path("forstatus",views.Forstatus,name="forstatus"),
    path("fprofile",views.Fprofile,name="fprofile"),
    path("facc",views.Facc,name="facc"),
    path("frej",views.Frej,name="frej"),
    path("accept/",views.Accept,name="accept"),
    path("reject/",views.Rejectpg,name="reject"),
    path("pick/",views.pickdrop,name="pick"),
    path("changepic/",views.Changepic,name="changepic"),
    path("uservehicle/<int:pk>",views.Uservehicle,name="uservehicle"),
    path("pdstatus/<int:pk>",views.Pdstatus,name="pdstatus"),
    path("servicedon/<int:pk>",views.Servicedon,name="servicedon"),
    path("foremanupdate",views.Foremanupdates,name="foremanupdate"),

    #Admin
    path("adminpanel/",views.Adminpanel,name="adminpanel"),
    path("aacc",views.Aacc,name="aacc"),
    path("database",views.Database,name="database"),
    path("invoice",views.Invoice,name="invoice"),
    path("generateinvoice/<int:pk>",views.Generateinvoice,name="generateinvoice"),
    path("bill/",views.Bill,name="bill"),
    path("orderacc",views.Orderacc,name="orderacc"),
    path("orderdel/<int:pk>",views.Orderdel,name="orderdel"),
    path("userorder/<int:pk>",views.Userorder,name="userorder"),
    path("accpayment",views.Accpayment,name="accpayment"),
    path("adminupdate",views.Adminupdates,name="adminupdate"),
    path("vehicleverify",views.Vehicleverify,name="vehicleverify"),
    path("vehapproval/<int:pk>",views.Vehapproval,name="vehapproval"),
    path("vehreject/<int:pk>",views.Vehreject,name="vehreject"),
    path("vehdetails",views.vehdetails,name="vehdetails"),
    path("chat",views.Chat,name="chat"),


    path("pdfgenerate/<int:pk>",views.Pdfgenerate,name="pdfgenerate"),
]

