# Generated by Django 2.0 on 2020-02-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accesories_name', models.CharField(max_length=30)),
                ('Accesories_type', models.CharField(max_length=30)),
                ('Accesories_price', models.IntegerField()),
                ('Accesories_description', models.CharField(max_length=100)),
                ('Accesories_photo', models.ImageField(default='patient_icon.png', upload_to='main_app/img/accesories')),
                ('Accesories_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=10)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=10)),
                ('vehicle_mileage', models.IntegerField()),
                ('vehicle_appdate', models.DateField()),
                ('vehicle_apptime', models.TimeField()),
                ('vehicle_need', models.CharField(max_length=500)),
                ('vehicle_username', models.CharField(max_length=20)),
                ('vehicle_useremail', models.EmailField(max_length=254)),
                ('vehicle_info', models.CharField(max_length=50)),
                ('vehicle_status', models.CharField(max_length=10)),
                ('vehicle_address', models.CharField(default='', max_length=30)),
                ('vehicle_contact', models.IntegerField(default='0000000000')),
                ('vehicle_mode', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_date', models.DateField()),
                ('Cart_itemqty', models.IntegerField()),
                ('Cart_price', models.IntegerField()),
                ('Cart_description', models.CharField(max_length=30)),
                ('Accesories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Accesories')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=459)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chatbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chatbox_keyword', models.CharField(max_length=30)),
                ('predefined_id', models.CharField(max_length=30)),
                ('Chatbox_action', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_name', models.CharField(default='', max_length=20)),
                ('Feedback_email', models.EmailField(default='', max_length=20)),
                ('Feedback_subject', models.CharField(default='', max_length=500)),
                ('Feedback_info', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foreman_name', models.CharField(max_length=30)),
                ('Foreman_jdate', models.DateField(auto_now_add=True)),
                ('Foreman_worktime', models.IntegerField(default='6')),
                ('Foreman_address', models.CharField(default='', max_length=30)),
                ('Foreman_contact', models.IntegerField()),
                ('Foreman_email', models.EmailField(max_length=30)),
                ('Foreman_password', models.CharField(default='', max_length=20)),
                ('Foreman_gender', models.CharField(max_length=30)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Order_date', models.DateField()),
                ('Order_status', models.CharField(max_length=30)),
                ('Order_approxtime', models.IntegerField()),
                ('Accesories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Accesories')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_type', models.CharField(max_length=30)),
                ('Payment_price', models.IntegerField()),
                ('Payment_status', models.CharField(max_length=30)),
                ('Payment_recievedate', models.DateField()),
                ('Card_type', models.CharField(max_length=30)),
                ('Card_number', models.IntegerField()),
                ('OnlinePayment_otp', models.CharField(max_length=6)),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_appdate', models.DateField()),
                ('service_type', models.CharField(max_length=30)),
                ('service_validity', models.CharField(max_length=30)),
                ('service_info', models.CharField(max_length=300)),
                ('service_estimatecost', models.IntegerField()),
                ('service_status', models.CharField(max_length=30)),
                ('service_approx_time', models.DateTimeField()),
                ('service_completion_time', models.DateTimeField()),
                ('service_cost', models.IntegerField()),
                ('foremanid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Foreman')),
            ],
        ),
        migrations.CreateModel(
            name='Servicevehicle',
            fields=[
                ('service_vehregno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('service_vehname', models.CharField(max_length=30)),
                ('service_vehtype', models.CharField(max_length=30)),
                ('service_vehcom', models.CharField(max_length=30)),
                ('foremanid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Foreman')),
            ],
        ),
        migrations.CreateModel(
            name='Usedvehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usedvehicle_regno', models.CharField(max_length=30)),
                ('Usedvehicle_type', models.CharField(max_length=30)),
                ('Usedvehicle_company', models.CharField(max_length=30)),
                ('Usedvehicle_modelname', models.CharField(max_length=30)),
                ('Usedvehicle_regdate', models.DateField()),
                ('Usedvehicle_vehcolor', models.CharField(max_length=30)),
                ('Usedvehicle_year', models.IntegerField()),
                ('Usedvehicle_chasisno', models.CharField(max_length=30)),
                ('Usedvehicle_km', models.IntegerField()),
                ('Usedvehicle_price', models.IntegerField()),
                ('Usedvehicle_email', models.EmailField(max_length=254)),
                ('Usedvehicle_phone', models.IntegerField()),
                ('Usedvehicle_rcphoto', models.ImageField(default='patient_icon.png', upload_to='main_app/img/usedvehicles')),
                ('Usedvehicle_photo', models.ImageField(default='patient_icon.png', upload_to='main_app/img/usedvehicles')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('userpass', models.CharField(max_length=30)),
                ('usergender', models.CharField(max_length=30)),
                ('usermail', models.EmailField(max_length=30)),
                ('useraddress', models.CharField(max_length=30)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiclebuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testslotdate', models.DateTimeField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleseller_regdate', models.DateField()),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='usedvehicle',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='servicevehicle',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_vehregno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Servicevehicle'),
        ),
        migrations.AddField(
            model_name='payment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='chatbox',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Serviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Service'),
        ),
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
    ]
