# Generated by Django 2.0 on 2020-02-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(max_length=10)),
                ('membership_fname', models.CharField(max_length=10)),
                ('membership_email', models.EmailField(max_length=254)),
                ('membership_phno', models.IntegerField()),
                ('membership_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='Feedback_phono',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='usedvehicle',
            name='Usedvehicle_info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='userremservice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usedvehicle',
            name='Usedvehicle_photo',
            field=models.ImageField(default='patient_icon.png', upload_to='main_app/static/main_app/img/usedvehicles'),
        ),
        migrations.AlterField(
            model_name='usedvehicle',
            name='Usedvehicle_rcphoto',
            field=models.ImageField(default='patient_icon.png', upload_to='main_app/static/main_app/img/usedvehicles'),
        ),
        migrations.AddField(
            model_name='member',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
    ]
