# Generated by Django 2.0 on 2020-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200215_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userphone',
            field=models.IntegerField(default='999'),
        ),
    ]
