# Generated by Django 2.0 on 2020-03-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_userphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('FkPID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Accesories')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderMasterTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillingAddress', models.CharField(max_length=250)),
                ('CDate', models.DateTimeField(auto_now=True)),
                ('BillTotal', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userphone',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='ordermastertbl',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='FkOrderMasterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.OrderMasterTbl'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='carttbl',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
    ]
