# Generated by Django 2.0 on 2020-03-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200313_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('FkPID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Accesories')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
        ),
    ]
