# Generated by Django 2.0 on 2020-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_cartx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartx',
            name='Name',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
