# Generated by Django 2.0 on 2020-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_cartx_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartx',
            name='Photo',
            field=models.ImageField(default='patient_icon.png', upload_to='main_app/img/cart'),
        ),
    ]
