# Generated by Django 2.0 on 2020-03-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_cartx_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartx',
            name='Qty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cartx',
            name='Total',
            field=models.CharField(max_length=20),
        ),
    ]
