# Generated by Django 2.0 on 2020-03-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200314_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='otp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
