# Generated by Django 2.0 on 2020-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200314_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='otp',
            field=models.BigIntegerField(null=True),
        ),
    ]
