# Generated by Django 2.0 on 2020-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200314_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='otp',
            field=models.IntegerField(default=999),
        ),
    ]
