# Generated by Django 2.0 on 2020-03-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='OnlinePayment_otp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Order_id',
        ),
    ]
