# Generated by Django 2.0 on 2020-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200314_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_recievedate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
