# Generated by Django 2.0 on 2020-03-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200314_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Paymentstatus',
        ),
    ]
