# Generated by Django 2.0 on 2020-03-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200314_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartx',
            name='Price',
            field=models.IntegerField(default='10'),
        ),
    ]
