# Generated by Django 2.0 on 2020-03-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20200316_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
