# Generated by Django 2.0 on 2020-03-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_user_usedvehicle_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Usedvehicle_photo',
            new_name='userphoto',
        ),
    ]
