# Generated by Django 2.0 on 2020-03-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200320_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphoto',
            field=models.ImageField(default='main_app/static/main_app/img/avtar.jpg', upload_to='main_app/static/main_app/img/user'),
        ),
    ]
