# Generated by Django 2.0 on 2020-03-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_foreman_foreman_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceaccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_number', models.CharField(max_length=10)),
                ('veh_year', models.IntegerField()),
                ('veh_type', models.CharField(max_length=10)),
                ('veh_mileage', models.IntegerField()),
                ('veh_appdate', models.DateField()),
                ('veh_apptime', models.TimeField()),
                ('veh_need', models.CharField(max_length=500)),
                ('veh_username', models.CharField(max_length=20)),
                ('veh_useremail', models.EmailField(max_length=254)),
                ('veh_info', models.CharField(max_length=50)),
                ('veh_status', models.CharField(max_length=10)),
                ('veh_address', models.CharField(default='', max_length=30)),
                ('veh_contact', models.IntegerField(default='0000000000')),
                ('veh_mode', models.CharField(default='', max_length=10)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='servicereject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rej_number', models.CharField(max_length=10)),
                ('rej_year', models.IntegerField()),
                ('rej_type', models.CharField(max_length=10)),
                ('rej_mileage', models.IntegerField()),
                ('rej_appdate', models.DateField()),
                ('rej_apptime', models.TimeField()),
                ('rej_need', models.CharField(max_length=500)),
                ('rej_username', models.CharField(max_length=20)),
                ('rej_useremail', models.EmailField(max_length=254)),
                ('rej_info', models.CharField(max_length=50)),
                ('rej_status', models.CharField(max_length=10)),
                ('rej_address', models.CharField(default='', max_length=30)),
                ('rej_contact', models.IntegerField(default='0000000000')),
                ('rej_mode', models.CharField(default='', max_length=10)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
        ),
    ]
