# Generated by Django 2.0 on 2020-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccept',
            name='veh_pdstatus',
            field=models.CharField(default='', max_length=10),
        ),
    ]
