# Generated by Django 2.0 on 2020-03-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_pickup_forid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='forid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.Category'),
        ),
    ]
