# Generated by Django 2.0 on 2020-03-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20200326_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicedone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_number', models.CharField(default='', max_length=10)),
                ('ser_year', models.IntegerField(default='')),
                ('ser_type', models.CharField(default='', max_length=10)),
                ('ser_mileage', models.IntegerField(default='')),
                ('ser_appdate', models.DateField(default='2020-11-03')),
                ('ser_apptime', models.TimeField(default='11:03:PM')),
                ('ser_need', models.CharField(default='', max_length=500)),
                ('ser_username', models.CharField(default='', max_length=20)),
                ('ser_useremail', models.EmailField(default='', max_length=254)),
                ('ser_info', models.CharField(default='', max_length=50)),
                ('ser_status', models.CharField(default='', max_length=10)),
                ('ser_address', models.CharField(default='', max_length=30)),
                ('ser_contact', models.IntegerField(default='0000000000')),
                ('ser_mode', models.CharField(default='', max_length=10)),
                ('ser_pdstatus', models.CharField(default='', max_length=10)),
                ('forid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
                ('userid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='foremanid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.Foreman'),
        ),
    ]
