# Generated by Django 2.0 on 2020-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20200326_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedone',
            name='ser_details',
            field=models.CharField(default='', max_length=250),
        ),
    ]
