# Generated by Django 2.0 on 2020-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_servicedone_ser_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedone',
            name='ser_payment',
            field=models.CharField(default='', max_length=10),
        ),
    ]
