# Generated by Django 2.0 on 2020-04-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_servicedone_ser_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedone',
            name='ser_payment',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
