# Generated by Django 2.0 on 2020-04-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20200401_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedone',
            name='veh_bill',
            field=models.IntegerField(default=''),
        ),
    ]
