# Generated by Django 2.0 on 2020-04-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_servicedone_veh_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedone',
            name='veh_bill',
            field=models.IntegerField(default='0000'),
        ),
    ]
