# Generated by Django 2.0 on 2020-04-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_auto_20200401_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedone',
            old_name='veh_bill',
            new_name='ser_bill',
        ),
    ]
