# Generated by Django 2.0 on 2020-04-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_auto_20200401_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedvehicle',
            name='Usedvehicle_verify',
            field=models.BooleanField(default='False'),
        ),
    ]
