# Generated by Django 2.0 on 2020-04-03 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_usedvehicle_usedvehicle_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
