# Generated by Django 2.0 on 2020-04-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='answer',
            field=models.CharField(default='hii', max_length=200),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(default='hii', max_length=200),
        ),
    ]
