# Generated by Django 2.0 on 2020-04-07 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_auto_20200407_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
