# Generated by Django 2.0 on 2020-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_chat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useraddress',
            field=models.CharField(max_length=100),
        ),
    ]
