# Generated by Django 2.0 on 2020-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_auto_20200516_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesories',
            name='like',
            field=models.IntegerField(default=1),
        ),
    ]
